services:
  web:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK:-traefik}"
      - "traefik.http.routers.sebo-web.rule=Host(`sebo.nortemtsistemas.com.br`)"
      - "traefik.http.routers.sebo-web.entrypoints=websecure"
      - "traefik.http.routers.sebo-web.tls.certresolver=myresolver"
      - "traefik.http.services.sebo-web.loadbalancer.server.port=80"
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik}
